// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

// public type Lecturer record {
//     string staffNumber?;
//     string officeNumber?;
//     string staffName?;
//     string title?;
//     string[] courses?;
// };

// public type Course record {
//     string courseCode?;
//     string courseName?;
//     int nqfLevel?;
// };
